# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20171021_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='quote',
        ),
        migrations.AddField(
            model_name='like',
            name='quote_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
